# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d4aa77e650c56482e9d03e02ff2d051"
application_url = "https://aluminium-adolescent-colors-swedish.trycloudflare.com"
embedded = true
name = "product_stories"
handle = "product_stories-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_files,read_files,read_themes,write_themes,write_inventory"

[auth]
redirect_urls = [
  "https://aluminium-adolescent-colors-swedish.trycloudflare.com/auth/callback",
  "https://aluminium-adolescent-colors-swedish.trycloudflare.com/auth/shopify/callback",
  "https://aluminium-adolescent-colors-swedish.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = true

[build]
dev_store_url = "reelstestproject.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
